### ISSUE TITLE
Can not use the plugin.

### ISSUE THREAD

**Issue by uginf0urth** [iberianpig/fusuma-plugin-sendkey#2]
Hello, can u help me, please? I installed your plugin for Fusuma, but I can not run it.
Log:
```
$ sudo gem install fusuma-plugin-sendkey
Successfully installed fusuma-plugin-sendkey-0.2.1
Parsing documentation for fusuma-plugin-sendkey-0.2.1
Done installing documentation for fusuma-plugin-sendkey after 0 seconds
1 gem installed

```
```
$ fusuma-sendkey -l
Traceback (most recent call last):
	14: from /usr/local/bin/fusuma-sendkey:23:in `<main>'
	13: from /usr/local/bin/fusuma-sendkey:23:in `load'
	12: from /var/lib/gems/2.5.0/gems/fusuma-plugin-sendkey-0.2.1/exe/fusuma-sendkey:5:in `<top (required)>'
	11: from /var/lib/gems/2.5.0/gems/fusuma-plugin-sendkey-0.2.1/exe/fusuma-sendkey:5:in `require_relative'
	10: from /var/lib/gems/2.5.0/gems/fusuma-plugin-sendkey-0.2.1/lib/fusuma/plugin/sendkey/keyboard.rb:3:in `<top (required)>'
	 9: from /var/lib/gems/2.5.0/gems/fusuma-plugin-sendkey-0.2.1/lib/fusuma/plugin/sendkey/keyboard.rb:3:in `require_relative'
	 8: from /var/lib/gems/2.5.0/gems/fusuma-plugin-sendkey-0.2.1/lib/fusuma/plugin/sendkey/device.rb:3:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /var/lib/gems/2.5.0/gems/evdev-1.0.0/lib/evdev.rb:2:in `<top (required)>'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /var/lib/gems/2.5.0/gems/libevdev-1.0.0/lib/libevdev.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
```
What am I doing wrong?

**Comment by uginf0urth** [comment]
oh. sorry it is my first time with ruby. I found answer in stackoverflow. I needed to install `gem install bundler`
